In [56]:
import numpy as np

nPoints = 5
nColours = 4


def generateCombinations(nPoints, nColours):
    nCombinations = nColours**nPoints
    totalCombinations = [np.array([i,j,k,l,m]) for i in range(4) for j in range(4) for k in range(4) for l in range(4) for m in range(4)]
    return np.array(totalCombinations)


def checkSequence(playerSequence,masterSequence):
    nBlack = sum([1 for p, m in zip(playerSequence, masterSequence) if p==m])
    nWhite = sum([1 for p, m in zip(playerSequence, masterSequence) if (p in masterSequence and p!=m)])
    return nBlack, nWhite
                

def constrainChoice(combinations,playerSequence,check):
     for possible in combinations:
            
            if checkSequence(playerSequence,possible)==check or (possible == playerSequence).all():
                np.delete(combinations,possible)

def printColors(array):
    colorMap = ["R","Y","B","G"]
    print("|",[colorMap[i] for i in array],"|")
    

def makeChoice(combinations):
    return combinations[np.random.randint(combinations.shape[0]),:]
    
    
totalCombinations = generateCombinations(nPoints,nColours)

combinationPool = totalCombinations

print(combinationPool)


masterSequence = makeChoice(combinationPool)

playerSequence = makeChoice(combinationPool)

print("MASTER SEQUENCE:")
printColors(masterSequence)


maxIter = 10000

kBlack, kWhite, nIter = 0,0,0

while(True):

    print("PLAYER SEQUENCE: {0}".format(nIter+1))
    printColors(playerSequence)
    
    check = checkSequence(playerSequence,masterSequence)
    constrainChoice(combinationPool,playerSequence,check)
    
    kBlack,kWhite = check
    
    playerSequence = makeChoice(combinationPool)
    
    nIter+=1
    
    if kBlack == nPoints or nIter > maxIter:
        break
    



[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 2]
 ...
 [3 3 3 3 1]
 [3 3 3 3 2]
 [3 3 3 3 3]]
MASTER SEQUENCE:
| ['R', 'Y', 'R', 'B', 'R'] |
PLAYER SEQUENCE: 1
| ['B', 'R', 'Y', 'R', 'R'] |
PLAYER SEQUENCE: 2
| ['G', 'G', 'Y', 'R', 'B'] |
PLAYER SEQUENCE: 3
| ['Y', 'B', 'R', 'G', 'G'] |
PLAYER SEQUENCE: 4
| ['G', 'G', 'B', 'R', 'G'] |
PLAYER SEQUENCE: 5
| ['B', 'R', 'G', 'R', 'R'] |
PLAYER SEQUENCE: 6
| ['G', 'G', 'B', 'R', 'Y'] |
PLAYER SEQUENCE: 7
| ['B', 'G', 'Y', 'B', 'Y'] |
PLAYER SEQUENCE: 8
| ['R', 'R', 'B', 'B', 'B'] |
PLAYER SEQUENCE: 9
| ['B', 'Y', 'G', 'R', 'G'] |
PLAYER SEQUENCE: 10
| ['G', 'Y', 'R', 'Y', 'B'] |
PLAYER SEQUENCE: 11
| ['R', 'G', 'R', 'Y', 'B'] |
PLAYER SEQUENCE: 12
| ['B', 'B', 'B', 'B', 'B'] |
PLAYER SEQUENCE: 13
| ['R', 'G', 'G', 'B', 'Y'] |
PLAYER SEQUENCE: 14
| ['B', 'Y', 'B', 'Y', 'Y'] |
PLAYER SEQUENCE: 15
| ['G', 'R', 'R', 'B', 'Y'] |
PLAYER SEQUENCE: 16
| ['G', 'R', 'Y', 'G', 'B'] |
PLAYER SEQUENCE: 17
| ['R', 'G', 'R', 'B', 'Y'] |
PLAYER SEQUENCE: 18
| ['G', 

PLAYER SEQUENCE: 163
| ['G', 'Y', 'B', 'R', 'G'] |
PLAYER SEQUENCE: 164
| ['B', 'R', 'B', 'Y', 'B'] |
PLAYER SEQUENCE: 165
| ['G', 'G', 'Y', 'Y', 'B'] |
PLAYER SEQUENCE: 166
| ['B', 'B', 'B', 'G', 'G'] |
PLAYER SEQUENCE: 167
| ['R', 'B', 'G', 'G', 'Y'] |
PLAYER SEQUENCE: 168
| ['G', 'G', 'Y', 'G', 'Y'] |
PLAYER SEQUENCE: 169
| ['R', 'Y', 'G', 'G', 'B'] |
PLAYER SEQUENCE: 170
| ['G', 'G', 'G', 'R', 'G'] |
PLAYER SEQUENCE: 171
| ['B', 'B', 'Y', 'R', 'G'] |
PLAYER SEQUENCE: 172
| ['B', 'G', 'G', 'R', 'G'] |
PLAYER SEQUENCE: 173
| ['Y', 'R', 'G', 'G', 'G'] |
PLAYER SEQUENCE: 174
| ['G', 'R', 'B', 'B', 'G'] |
PLAYER SEQUENCE: 175
| ['R', 'G', 'Y', 'B', 'Y'] |
PLAYER SEQUENCE: 176
| ['G', 'Y', 'B', 'G', 'G'] |
PLAYER SEQUENCE: 177
| ['G', 'B', 'Y', 'R', 'B'] |
PLAYER SEQUENCE: 178
| ['R', 'B', 'G', 'B', 'Y'] |
PLAYER SEQUENCE: 179
| ['Y', 'Y', 'Y', 'B', 'R'] |
PLAYER SEQUENCE: 180
| ['G', 'Y', 'G', 'R', 'Y'] |
PLAYER SEQUENCE: 181
| ['B', 'B', 'Y', 'G', 'G'] |
PLAYER SEQUENCE: 182
| ['G', 'G

PLAYER SEQUENCE: 327
| ['R', 'Y', 'Y', 'G', 'R'] |
PLAYER SEQUENCE: 328
| ['B', 'G', 'B', 'R', 'B'] |
PLAYER SEQUENCE: 329
| ['R', 'Y', 'B', 'G', 'B'] |
PLAYER SEQUENCE: 330
| ['Y', 'Y', 'B', 'B', 'B'] |
PLAYER SEQUENCE: 331
| ['Y', 'G', 'R', 'B', 'G'] |
PLAYER SEQUENCE: 332
| ['R', 'Y', 'B', 'Y', 'Y'] |
PLAYER SEQUENCE: 333
| ['G', 'R', 'B', 'R', 'B'] |
PLAYER SEQUENCE: 334
| ['G', 'B', 'Y', 'B', 'B'] |
PLAYER SEQUENCE: 335
| ['R', 'Y', 'R', 'B', 'B'] |
PLAYER SEQUENCE: 336
| ['R', 'G', 'R', 'Y', 'G'] |
PLAYER SEQUENCE: 337
| ['Y', 'Y', 'R', 'Y', 'G'] |
PLAYER SEQUENCE: 338
| ['Y', 'B', 'G', 'R', 'Y'] |
PLAYER SEQUENCE: 339
| ['R', 'Y', 'G', 'R', 'G'] |
PLAYER SEQUENCE: 340
| ['Y', 'B', 'R', 'G', 'R'] |
PLAYER SEQUENCE: 341
| ['Y', 'G', 'Y', 'Y', 'G'] |
PLAYER SEQUENCE: 342
| ['R', 'Y', 'R', 'Y', 'G'] |
PLAYER SEQUENCE: 343
| ['R', 'R', 'R', 'B', 'G'] |
PLAYER SEQUENCE: 344
| ['G', 'R', 'G', 'R', 'B'] |
PLAYER SEQUENCE: 345
| ['R', 'B', 'B', 'B', 'R'] |
PLAYER SEQUENCE: 346
| ['G', 'G

In [ ]:
def find_correct(actual, guess):
    '''Finds the sum of all correct matches.'''
    return sum([1 for (a, b) in zip(actual, guess) if a == b])


def remove_correct(actual, guess):
    '''Removes all correct matches from two "rows"'''
    actual2 = [a for (a, b) in zip(actual, guess) if a != b]
    guess2 = [b for (a, b) in zip(actual, guess) if a != b]
    return actual2, guess2


def find_close(actual, guess):
    '''Finds the sum of all close matches.'''
    actual, guess = remove_correct(actual, guess)

    close = 0
    for possible in guess:
        if possible in actual:
            del actual[actual.index(possible)]
            close += 1
    return close


def get_feedback(actual, guess):
    '''Compares two "rows" to each other and returns feedback.'''
    return Feedback(find_correct(actual, guess), find_close(actual, guess))


In [35]:

'''
Mastermind solver
Given feedback from a game of mastermind, makes guesses to try and
determine the answer.
'''

import itertools
import collections


Feedback = collections.namedtuple('Feedback', ['correct', 'close'])


def generate_initial_pool(choices, holes):
    '''Generates the initial set of possible answers.'''
    return list(itertools.product(*[range(choices) for _ in range(holes)]))


def find_correct(actual, guess):
    '''Finds the sum of all correct matches.'''
    return sum([1 for (a, b) in zip(actual, guess) if a == b])


def remove_correct(actual, guess):
    '''Removes all correct matches from two "rows"'''
    actual2 = [a for (a, b) in zip(actual, guess) if a != b]
    guess2 = [b for (a, b) in zip(actual, guess) if a != b]
    return actual2, guess2


def find_close(actual, guess):
    '''Finds the sum of all close matches.'''
    actual, guess = remove_correct(actual, guess)

    close = 0
    for possible in guess:
        if possible in actual:
            del actual[actual.index(possible)]
            close += 1
    return close


def get_feedback(actual, guess):
    '''Compares two "rows" to each other and returns feedback.'''
    return Feedback(find_correct(actual, guess), find_close(actual, guess))


def is_match(guess, feedback, possible):
    '''Returns true if hypothetical could be the answer given the feedback
    and the guess'''
    return feedback == get_feedback(possible, guess)


def filter_pool(pool, guess, feedback):
    '''Filters through the pool of possibilities and removes ones which
    couldn't possibly be the answer.'''
    for possible in pool:
        if is_match(guess, feedback, possible) and (possible != guess):
            yield possible


def make_guess(pool, feedback):
    '''Makes an educated guess between the pool of possibilities and
    the user feedback.'''
    min_length = float('infinity')
    best_choice = None
    for possible in pool:
        length = len(list(filter_pool(pool, possible, feedback)))
        if min_length > length:
            min_length = length
            best_choice = possible
    return best_choice


def play():
    '''Plays a complete game of mastermind, and collects user input.'''
    choices = int(input("Number of numbers? "), 10)
    holes = int(input("Number of spaces?  "), 10)

    pool = generate_initial_pool(choices, holes)
    guess = [0 if (i < (holes / 2)) else 1 for i in range(holes)]
    while True:
        print("Try this: {0}".format(guess))
        correct = int(raw_input("    # Red pegs?   "))
        close = int(input("    # White pegs? "))

        feedback = Feedback(correct, close)
        if feedback.correct == holes:
            break
        pool = list(filter_pool(pool, guess, feedback))
        print ("{0} possible choices left. Thinking...\n".format(len(pool)))

        guess = make_guess(pool, feedback)
    print ("\nYou win!")

play()



Number of numbers? 4
Number of spaces?  4
Try this: [0, 0, 1, 1]


NameError: name 'raw_input' is not defined