In [37]:
import numpy as np

nPoints = 5
nColours = 4


def generateCombinations(nPoints, nColours):
    nCombinations = nColours**nPoints
    totalCombinations = [(i,j,k,l,m) for i in range(4) for j in range(4) for k in range(4) for l in range(4) for m in range(4)]
    return np.array(totalCombinations)


def checkSequence(playerSequence,masterSequence):
    nBlack = sum([1 for p, m in zip(playerSequence, masterSequence) if p==m])
    nWhite = sum([1 for p, m in zip(playerSequence, masterSequence) if (p in masterSequence and p!=m)])
    return nBlack, nWhite
                
guess = [1,2,3,4,5]
master = [1,2,1,4,1]

print(generateCombinations(nPoints, nColours))
checkSequence(guess, master)

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 2]
 ...
 [3 3 3 3 1]
 [3 3 3 3 2]
 [3 3 3 3 3]]


(3, 0)

In [ ]:
def find_correct(actual, guess):
    '''Finds the sum of all correct matches.'''
    return sum([1 for (a, b) in zip(actual, guess) if a == b])


def remove_correct(actual, guess):
    '''Removes all correct matches from two "rows"'''
    actual2 = [a for (a, b) in zip(actual, guess) if a != b]
    guess2 = [b for (a, b) in zip(actual, guess) if a != b]
    return actual2, guess2


def find_close(actual, guess):
    '''Finds the sum of all close matches.'''
    actual, guess = remove_correct(actual, guess)

    close = 0
    for possible in guess:
        if possible in actual:
            del actual[actual.index(possible)]
            close += 1
    return close


def get_feedback(actual, guess):
    '''Compares two "rows" to each other and returns feedback.'''
    return Feedback(find_correct(actual, guess), find_close(actual, guess))


In [35]:

'''
Mastermind solver
Given feedback from a game of mastermind, makes guesses to try and
determine the answer.
'''

import itertools
import collections


Feedback = collections.namedtuple('Feedback', ['correct', 'close'])


def generate_initial_pool(choices, holes):
    '''Generates the initial set of possible answers.'''
    return list(itertools.product(*[range(choices) for _ in range(holes)]))


def find_correct(actual, guess):
    '''Finds the sum of all correct matches.'''
    return sum([1 for (a, b) in zip(actual, guess) if a == b])


def remove_correct(actual, guess):
    '''Removes all correct matches from two "rows"'''
    actual2 = [a for (a, b) in zip(actual, guess) if a != b]
    guess2 = [b for (a, b) in zip(actual, guess) if a != b]
    return actual2, guess2


def find_close(actual, guess):
    '''Finds the sum of all close matches.'''
    actual, guess = remove_correct(actual, guess)

    close = 0
    for possible in guess:
        if possible in actual:
            del actual[actual.index(possible)]
            close += 1
    return close


def get_feedback(actual, guess):
    '''Compares two "rows" to each other and returns feedback.'''
    return Feedback(find_correct(actual, guess), find_close(actual, guess))


def is_match(guess, feedback, possible):
    '''Returns true if hypothetical could be the answer given the feedback
    and the guess'''
    return feedback == get_feedback(possible, guess)


def filter_pool(pool, guess, feedback):
    '''Filters through the pool of possibilities and removes ones which
    couldn't possibly be the answer.'''
    for possible in pool:
        if is_match(guess, feedback, possible) and (possible != guess):
            yield possible


def make_guess(pool, feedback):
    '''Makes an educated guess between the pool of possibilities and
    the user feedback.'''
    min_length = float('infinity')
    best_choice = None
    for possible in pool:
        length = len(list(filter_pool(pool, possible, feedback)))
        if min_length > length:
            min_length = length
            best_choice = possible
    return best_choice


def play():
    '''Plays a complete game of mastermind, and collects user input.'''
    choices = int(input("Number of numbers? "), 10)
    holes = int(input("Number of spaces?  "), 10)

    pool = generate_initial_pool(choices, holes)
    guess = [0 if (i < (holes / 2)) else 1 for i in range(holes)]
    while True:
        print("Try this: {0}".format(guess))
        correct = int(raw_input("    # Red pegs?   "))
        close = int(input("    # White pegs? "))

        feedback = Feedback(correct, close)
        if feedback.correct == holes:
            break
        pool = list(filter_pool(pool, guess, feedback))
        print ("{0} possible choices left. Thinking...\n".format(len(pool)))

        guess = make_guess(pool, feedback)
    print ("\nYou win!")

play()



Number of numbers? 4
Number of spaces?  4
Try this: [0, 0, 1, 1]


NameError: name 'raw_input' is not defined